version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: samaker_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: samaker
      POSTGRES_PASSWORD: samaker_pass
      POSTGRES_DB: samaker
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
